### PR TITLE
ignore tokens in comments

### PR DESCRIPTION
**Pull request by d12frosted**
Should fix https://github.com/d12frosted/fish-mode/issues/2.

### CODE REVIEW

**Comment by wwwjfy** [comment]
This is actually very difficult to fix perfectly without understanding the semantics.
For example, a `#` in a string would break the logic.
I need to take a while to see if this fix is good enough

**Comment by d12frosted** [comment]
Ah. You're right. `do_something " # "; begin ...` will be treated as `do_something "`.

And the space there stands for improving semantics. If the line contains only whitespaces and `#` it will be treated as comment line by other function. But if it's not - ` #` will seek for trailing comment. We just need to improve how it removes trailing comment from line.

**Comment by d12frosted** [comment]
Sorry for delay. So this is my second attempt to fix this issue.

**Comment by wwwjfy** [comment]
I'm not sure using regular expression to remove strings is a good idea, that it's difficult to have the correct re and it's easy to be over-complex. A few examples to break the logic:
- escaped double quote in a double-quoted string
- single quotes should be considered, so a double quote in a single-quoted string and vice versa
- the regular expression is greedy, so something useful between the first and last quotes are replaced

ps, s.el functions are used in the patch, which should be declared or avoided

**Comment by d12frosted** [comment]
> I'm not sure using regular expression to remove strings is a good idea, that it's difficult to have the correct re and it's easy to be over-complex.

Yeah, I agree that in general it's not so good to use them.

> escaped double quote in a double-quoted string

How does it break logic? Regexp is greedy, so it removes as much as possible, so `"hello \"begin\" world"` is removed totally. Am I missing anything here?

> single quotes should be considered

Ah, good points. Somehow I forgot about `'`. 

> the regular expression is greedy, so something useful between the first and last quotes are replaced

Could you elaborate on this too? The point of this regexp is to get rid of strings and then try to get trailing comment. Then `current-line` removes that trailing comment if it's found. So actually, function for getting trailing comment doesn't care at all about any non-comment strings. 

> ps, s.el functions are used in the patch, which should be declared or avoided
Ya, good point.

P. S. Following example breaks the logic:

```
set tmp 0 # "" hello begin
```

Because `""` is removed from string and trailing comment is "#  hello begin", and when it tries to remove it - it fails, so resulting string is `set tmp 0 # "" hello begin`. This makes me feel like it's good idea to parse string in a honest way. Like read string character by character and decide where comment starts. 

P. P. S. Thanks for your input!

**Comment by wwwjfy** [comment]
> How does it break logic? Regexp is greedy, so it removes as much as possible, so "hello \"begin\" world" is removed totally. Am I missing anything here?

Sorry, I didn't think it through. I was thinking in non-greedy re case with one escaped double quote.

> Could you elaborate on this too? The point of this regexp is to get rid of strings and then try to get trailing comment. Then current-line removes that trailing comment if it's found. So actually, function for getting trailing comment doesn't care at all about any non-comment strings.

e.g.
```
echo "test"; begin; "hello"
```

This will remove `begin` as well.

PS. strings can be in multiple lines, which will break line-based logic.

**Comment by d12frosted** [comment]
> Sorry, I didn't think it through. I was thinking in non-greedy re case with one escaped double quote.

It's ok :smile: 

> This will remove begin as well.
> PS. strings can be in multiple lines, which will break line-based logic.

Ah... right. It's really not that easy as I thought. Thanks for pointing out these cases. Have a topic to think about.

**Comment by wwwjfy** [comment]
This can be closed due to #24

**Pull request closed without merging**
